---
- hosts: node1
  become: yes
  tasks:
    - name: Instalar bind9
      apt: name=bind9 update_cache=yes

    - name: Configuracion bind9 
      copy:
        src: templates/named.conf.local
        dest: /etc/bind/named.conf.local

    - name: Configuracion zona directa
      copy:
        src: templates/db.iesgn.org
        dest: /var/cache/bind/db.iesgn.org

    - name: Configuracion zona inversa
      copy:
        src: templates/db.100.168.192
        dest: /var/cache/bind/db.100.168.192

    - name: restart bind9
      service:
        name: bind9
        state: restarted
