---
- hosts: nodo1
  become: yes
  tasks:
    - name: Instalar bind9
      apt: name=bind9 update_cache=yes

    - name: Cofiguración bind9
      copy:      
        src: templates/named.conf.local
        dest: /etc/bind/named.conf.local

    - name: Configurando zona directa
      copy:
        src: templates/db.iesgn.org
        dest: /var/cache/bind/db.iesgn.org

    - name: Configurando zona inversa
      copy:
        src: templates/db.69.168.192
        dest: /var/cache/bind/db.69.168.192

    - name: restart bind9
      become: yes
      service:
        name: bind9
        state: restarted

  handlers:
  - name: reinicio bind9
    service: name=bind9 state=restarted
